apiVersion: apps/v1                   #extensions/v1beta1
kind: Deployment
metadata:
  name: jpetstore-deployment
  labels:
    app: jpetstore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
       app: jpetstore-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jpetstore-app
    spec:
      containers:
      - image: docker.io/bokim/oke-jpetstore:master-0.1
        imagePullPolicy: Always
        name: jpetstore-app-container
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always

---

#apiVersion: v1
#kind: Service
#metadata:
#  name: jpetstore-svc
#spec:
#  type: LoadBalancer
#  selector:
#    app: jpetstore-app
#  ports:
#    - name: http
#      port: 80
#      targetPort: 8080
#      protocol: TCP
#      nodePort: 30080

